[package]
name = "taboom-vmm"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
nix = { workspace = true }
taboom-proto = { path = "../taboom-proto" }
